BuildRequires: llvm-devel cmake(zlib) cmake(libxml2)
# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate llvm-sys

Name:           rust-llvm-sys
Version:        201.0.0
Release:        %autorelease
Summary:        Bindings to LLVM's C API

License:        MIT
URL:            https://crates.io/crates/llvm-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Bindings to LLVM's C API.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+clang-sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clang-sys-devel %{_description}

This package contains library source intended for building other packages which
use the "clang-sys" feature of the "%{crate}" crate.

%files       -n %{name}+clang-sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+disable-alltargets-init-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+disable-alltargets-init-devel %{_description}

This package contains library source intended for building other packages which
use the "disable-alltargets-init" feature of the "%{crate}" crate.

%files       -n %{name}+disable-alltargets-init-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+force-dynamic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+force-dynamic-devel %{_description}

This package contains library source intended for building other packages which
use the "force-dynamic" feature of the "%{crate}" crate.

%files       -n %{name}+force-dynamic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+force-static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+force-static-devel %{_description}

This package contains library source intended for building other packages which
use the "force-static" feature of the "%{crate}" crate.

%files       -n %{name}+force-static-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no-llvm-linking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no-llvm-linking-devel %{_description}

This package contains library source intended for building other packages which
use the "no-llvm-linking" feature of the "%{crate}" crate.

%files       -n %{name}+no-llvm-linking-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prefer-dynamic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prefer-dynamic-devel %{_description}

This package contains library source intended for building other packages which
use the "prefer-dynamic" feature of the "%{crate}" crate.

%files       -n %{name}+prefer-dynamic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prefer-static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prefer-static-devel %{_description}

This package contains library source intended for building other packages which
use the "prefer-static" feature of the "%{crate}" crate.

%files       -n %{name}+prefer-static-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+strict-versioning-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strict-versioning-devel %{_description}

This package contains library source intended for building other packages which
use the "strict-versioning" feature of the "%{crate}" crate.

%files       -n %{name}+strict-versioning-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages which
use the "tempfile" feature of the "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
